### ISSUE TITLE
Some watched events randomly don't show up

### ISSUE THREAD

**Issue by ColonelJ** [tronprotocol/tronweb#51]
I'm using `await contract.Method().watch({resourceNode: 'solidityNode'}, (err, res) => {...});` used on a few different methods.

It seems that some of the events do not trigger the function at all and simply go missing, meaning that the Dapp has an incomplete view of the state updates.  This is a real nuisance.

I had the same events being listened to on both a Node.js instance and on some webpages using TronLink, and I discovered that the events that go missing are different for each instance (one page showed all the events).  This means that the problem is not with the contract invocations or the events themselves but something to do with the code that retrieves the events.

Looking at the code it only seems to check for events every 3 seconds and only gets events for the latest block, so it is possible that it could be completely missing blocks.  The getEvents function should check all blocks since the last time it was called, not just the latest block, and even if the interval is set for 20 seconds (simulating some sort of processing delay) it should still pick up all the events for the last few blocks to ensure that none are missed.

It is entirely possible that in a web page processing the UI could delay the getEvents function considerably, so that it gets called every 3 seconds cannot be relied upon.  Same in the server, if there are a bunch of events to process from one block that involve heavy processing each, then the next block will be missed, which is not acceptable.

**Comment by ColonelJ** [comment]
In case it might help anyone, this is the code I'm using instead of using `contract.Method().watch` to discover the events due to this problem (seems to work reliably for recent events):

```javascript
    let last_event_timestamp = Date.now() - 10000;
    let processing = false;
    setInterval(async () => {
        if (processing) return;
        processing = true;
        try {
            let events = [];
            let more_events =
                await tronWeb.getEventResult(CONTRACT_ADDRESS, {
                    onlyConfirmed: true,
                    sinceTimestamp: last_event_timestamp + 1,
                    sort: 'block_timestamp'
                });
            while (more_events.length
                   && more_events[more_events.length - 1].fingerprint) {
                events = events.concat(more_events);
                more_events =
                    await tronWeb.getEventResult(CONTRACT_ADDRESS, {
                        onlyConfirmed: true,
                        previousLastEventFingerprint:
                            more_events[more_events.length - 1].fingerprint,
                        sort: 'block_timestamp'
                    });
            }
            events = events.concat(more_events);
            if (events.length) {
                last_event_timestamp = events[events.length - 1].timestamp;
                for (let i = 0; i < events.length; ++i) {
                    if (events[i].name == 'Method') {
                        /*...*/
                    } else if (events[i].name == /*...*/) {
                        /*...*/
                    /*...*/
                    } else {
                        console.error('Unrecognized event name:', events[i].name);
                    }
                }
            }
        } catch (err) {
            console.error('Error getting events:', err);
        }
        processing = false;
    }, 3000);
```

This also has the advantage that it only does one request for all possible events that can be emitted by the contract.  If you wanted you could add the eventName parameter to the options for getEventResult so you wouldn't have to check the name.

Maybe the `contract.Method().watch` functionality could use logic similar to this to achieve the desired effect.

**Comment by sullof** [comment]
If you want to be sure you get all the events in a block, you can use TronGridJS API and retrieve the events by block. Look at https://github.com/TRON-US/trongrid-js/blob/master/test/unit/lib/block.test.js for examples.

**Comment by sullof** [comment]
To solve the issue we will add web sockets in the future.

**Comment by sullof** [comment]
About the code you wrote, you could submit a PR.

**Comment by forhas** [comment]
Hi @sullof,
Do you know if this one is expected to be resolved anytime soon?

**Comment by UnforgivenZZZ** [comment]
> Hi @sullof,
> Do you know if this one is expected to be resolved anytime soon?

we all left tron so maybe don't expected those issue to be fixed

**Comment by UnforgivenZZZ** [comment]
@forhas 
we all left tron so maybe don't expected those issue to be fixed

**Comment by forhas** [comment]
@UnforgivenZZZ thanks for clarifying.
Is the project still maintained (by anyone)?

**Comment by sullof** [comment]
It looks like last merge was 21 days ago by @jeancky.

**Comment by tigfamon** [comment]
@sullof , @forhas  is there any update on this issue? For our poker game, event listening is still not working correctly. Some events get lost.

**Comment by pryctoyogi** [comment]
@tigfamon I did not get the chance to test the latest version.
I've implemented my own manual solution:


```
setInterval(getEvents, tronBlockTime * pullCycle);

async function getEvents() {
    if (isRunning) {
        return;
    }
    isRunning = true;
    try {
        const latestBlock = await tronWeb.trx.getBlock('latest');
        let start = latestEventsBlockNumber;
        let end = latestBlock.block_header.raw_data.number;
        const eventsArr = [];
        for (let i = start; i < end; i++) {
            eventsPullingOptions.block_number = i;
            const events = await tronGrid.contract.getEvents(playzaContractAddress, eventsPullingOptions);
            const blockEvents = await events.data;
            if (blockEvents && blockEvents.length > 0) {
                eventsArr.push(...blockEvents);
            }
        }
        latestEventsBlockNumber = end;
        handleEvents(eventsArr);
    } catch (err) {
        // handle errors
        }
    } finally {
        isRunning = false;
    }
}
```

**Comment by 002love** [comment]
Any updates about this issue guys?

**Comment by 002love** [comment]
@sullof bro, is the problem still not fixed? Can you please correct this misunderstanding, this is a lot of problems 😔
